name: ai_hybrid_hub
description: "AI Hybrid Hub"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  auto_route: ^10.2.0
  drift: ^2.29.0
  elegant_notification: ^2.5.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_riverpod: ^3.0.1
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  gpt_markdown: ^1.1.4
  hive: ^2.2.3
  hive_ce: ^2.15.1
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  popover: ^0.4.0
  riverpod_annotation: ^3.0.1
  sqflite: ^2.4.2
  sqlite3_flutter_libs: ^0.5.40
  talker_flutter: ^5.0.2
  talker_riverpod_logger: ^5.0.2
  xml: ^6.6.1

dev_dependencies:
  auto_route_generator: ^10.2.5
  build_runner: ^2.7.1
  drift_dev: ^2.29.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: ^3.0.0
  json_serializable: ^6.11.1
  mockito: ^5.5.0
  riverpod_generator: ^3.0.1
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/js/
